### ISSUE TITLE
Add underline styles to footer nav links

### ISSUE THREAD

**Issue by cjg89** [UCF/Online-Child-Theme#15]
**Description**

White links in the footer need to have an underline applied to them on their default state.

**Why it's Important**

Helps distinguish them as links for accessibility purposes.

**Alternatives**

n/a

**Possible Implementation**

In src/scss/_footer.scss:
```scss
.site-footer {
  ...
  .menu-item a {
    text-decoration: underline;

    @include hover-focus {
      color: get-hover-color($white);
    }
  }
}
```

**Additional context**

n/a
